include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    OMIT_CLEAN_DEPLOY: 1
    COMPOSE_FILE: docker-compose.fail2ban-common.yml:docker-compose.fail2ban-input.yml:docker-compose.fail2ban-docker.yml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}-input ${CI_PROJECT_NAME}-docker
  environment:
    name: node1

.deploy-secondary-node:
  variables: &deploy-secondary-node-variables
    COMPOSE_FILE: docker-compose.fail2ban-common.yml:docker-compose.fail2ban-input.yml
    SERVICES_TO_DEPLOY: ${CI_PROJECT_NAME}-input
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}-input

.deploy-node2:
  environment: &deploy-node2-environment
    name: node2

.deploy-node3:
  environment: &deploy-node3-environment
    name: node3

deploy-node2-branch:
  extends: deploy-branch
  variables: *deploy-secondary-node-variables
  environment: *deploy-node2-environment

deploy-node2-tag:
  extends: deploy-tag
  variables: *deploy-secondary-node-variables
  environment: *deploy-node2-environment

deploy-node3-branch:
  extends: deploy-branch
  variables: *deploy-secondary-node-variables
  environment: *deploy-node3-environment

deploy-node3-tag:
  extends: deploy-tag
  variables: *deploy-secondary-node-variables
  environment: *deploy-node3-environment
