include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/lulu/docker-deploy.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/oracle/docker-deploy.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/museo/docker-deploy.yml'

stages:
  - deploy

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    OMIT_CLEAN_DEPLOY: 1
    COMPOSE_FILE: compose.common.yaml:compose.input.yaml:compose.docker.yaml
    SERVICES_TO_CHECK: fail2ban-input fail2ban-docker

.deploy-secondary-node:
  variables: &deploy-secondary-node-variables
    COMPOSE_FILE: compose.common.yaml:compose.input.yaml
    SERVICES_TO_DEPLOY: fail2ban-input
    SERVICES_TO_CHECK: fail2ban-input

deploy-branch-lulu:
  environment:
    name: lulu-node1

deploy-tag-lulu:
  environment:
    name: lulu-node1

deploy-node2-branch-lulu:
  extends: deploy-branch-lulu
  variables: *deploy-secondary-node-variables
  environment:
    name: lulu-node2

deploy-node2-tag-lulu:
  extends: deploy-tag-lulu
  variables: *deploy-secondary-node-variables
  environment:
    name: lulu-node2

deploy-node3-branch-lulu:
  extends: deploy-branch-lulu
  variables: *deploy-secondary-node-variables
  environment:
    name: lulu-node3

deploy-node3-tag-lulu:
  extends: deploy-tag-lulu
  variables: *deploy-secondary-node-variables
  environment:
    name: lulu-node3


deploy-branch-oracle:
  environment:
    name: oracle-node1

deploy-tag-oracle:
  environment:
    name: oracle-node1

deploy-node2-branch-oracle:
  extends: deploy-branch-oracle
  variables: *deploy-secondary-node-variables
  environment:
    name: oracle-node2

deploy-node2-tag-oracle:
  extends: deploy-tag-oracle
  variables: *deploy-secondary-node-variables
  environment:
    name: oracle-node2

deploy-node3-branch-oracle:
  extends: deploy-branch-oracle
  variables: *deploy-secondary-node-variables
  environment:
    name: oracle-node3

deploy-node3-tag-oracle:
  extends: deploy-tag-oracle
  variables: *deploy-secondary-node-variables
  environment:
    name: oracle-node3


deploy-branch-museo:
  environment:
    name: museo-node1

deploy-tag-museo:
  environment:
    name: museo-node1

deploy-node2-branch-museo:
  extends: deploy-branch-museo
  variables: *deploy-secondary-node-variables
  environment:
    name: museo-node2

deploy-node2-tag-museo:
  extends: deploy-tag-museo
  variables: *deploy-secondary-node-variables
  environment:
    name: museo-node2

deploy-node3-branch-museo:
  extends: deploy-branch-museo
  variables: *deploy-secondary-node-variables
  environment:
    name: museo-node3

deploy-node3-tag-museo:
  extends: deploy-tag-museo
  variables: *deploy-secondary-node-variables
  environment:
    name: museo-node3
