x-fail2ban:
  &fail2ban-common
  image: ${IMAGE_NAME:-crazymax/fail2ban}:${IMAGE_TAG:-latest}
  environment:
    TZ:
    F2B_LOG_LEVEL:
    F2B_DB_PURGE_AGE:
    IPTABLES_MODE:
  networks:
    host-net:
  cap_add:
    - NET_ADMIN
    - NET_RAW
  stop_grace_period: ${STOP_GRACE_PERIOD:-30s}
  healthcheck:
    disable: ${HEALTHCHECK_DISABLE:-false}

x-deploy:
  &deploy-common
  mode: global
  restart_policy:
    delay: ${RESTART_DELAY:-1s}
  resources:
    limits:
      cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
      memory: ${RESOURCES_LIMITS_MEMORY:-128M}
    reservations:
      cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

services:
  fail2ban-input:
    << : *fail2ban-common
    volumes:
      - input-data-vol:${DATA_VOL_PATH}
      - input-run-vol:${RUN_VOL_PATH}
      - ${SSH_LOG_PATH:-/var/log}:/log/ssh:ro
    configs:
      - source: default-jail-config
        target: ${DATA_VOL_PATH}/jail.d/default.conf
        mode: 0400
      - source: ssh-jail-config
        target: ${DATA_VOL_PATH}/jail.d/ssh.conf
        mode: 0400
    deploy:
      << : *deploy-common

  fail2ban-docker:
    << : *fail2ban-common
    volumes:
      - docker-data-vol:${DATA_VOL_PATH}
      - docker-run-vol:${RUN_VOL_PATH}
      - traefik-log-vol:/log/traefik:ro
    configs:
      - source: default-jail-config
        target: ${DATA_VOL_PATH}/jail.d/default.conf
        mode: 0400
      - source: traefik-filter-config
        target: ${DATA_VOL_PATH}/filter.d/traefik.conf
        mode: 0400
      - source: http-jail-config
        target: ${DATA_VOL_PATH}/jail.d/http.conf
        mode: 0400
    deploy:
      << : *deploy-common
      placement:
        constraints:
          - ${DOCKER_PLACEMENT_CONSTRAINTS_NAME} ${DOCKER_PLACEMENT_CONSTRAINTS_OPERATOR} ${DOCKER_PLACEMENT_CONSTRAINTS_VALUE}

networks:
  host-net:
    name: ${HOST_NET_NAME:-host}
    driver: ${HOST_NET_DRIVER:-host}
    external: true

volumes:
  input-data-vol:
    name: ${INPUT_DATA_VOL_NAME:-fail2ban-input-data-vol}
    driver: ${VOL_DRIVER}

  docker-data-vol:
    name: ${DOCKER_DATA_VOL_NAME:-fail2ban-docker-data-vol}
    driver: ${VOL_DRIVER}

  input-run-vol:
    name: ${INPUT_RUN_VOL_NAME:-fail2ban-input-run-vol}
    driver: ${VOL_DRIVER}

  docker-run-vol:
    name: ${DOCKER_RUN_VOL_NAME:-fail2ban-docker-run-vol}
    driver: ${VOL_DRIVER}

  traefik-log-vol:
    name: ${TRAEFIK_LOG_VOL_NAME:-traefik-log-vol}
    external: true

configs:
  default-jail-config:
    name: ${DEFAULT_JAIL_CONFIG_NAME:-fail2ban-default-jail-conf}
    file: ./config/jail.d/default.conf

  ssh-jail-config:
    name: ${SSH_JAIL_CONFIG_NAME:-fail2ban-ssh-jail-conf}
    file: ./config/jail.d/ssh.conf

  traefik-filter-config:
    name: ${TRAEFIK_FILTER_CONFIG_NAME:-fail2ban-traefik-filter-conf}
    file: ./config/filter.d/traefik.conf

  http-jail-config:
    name: ${HTTP_JAIL_CONFIG_NAME:-fail2ban-http-jail-conf}
    file: ./config/jail.d/http.conf
