services:
  fail2ban-docker:
    container_name: ${DOCKER_CONTAINER_NAME:-fail2ban-docker}
    volumes:
      - docker-data-vol:/data
      - traefik-log-vol:/log/traefik:ro
      - ./config/filter.d/traefik.conf:/data/filter.d/traefik.conf:ro
      - ./config/jail.d/default.conf:/data/jail.d/default.conf:ro
      - ./config/jail.d/http.conf:/data/jail.d/http.conf:ro
      - ./config/action.d/tts.conf:/data/action.d/tts.conf:ro
      - ./config/action.d/sendmail-whois-lines.local:/data/action.d/sendmail-whois-lines.local:ro

volumes:
  docker-data-vol:
    name: ${DOCKER_DATA_VOL_NAME:-fail2ban-docker-data-vol}

  traefik-log-vol:
    name: ${TRAEFIK_LOG_VOL_NAME:-traefik-log-vol}
    external: true
