version: '3.7'

x-fail2ban:
  &fail2ban-common
  image: ${IMAGE_NAME:-crazymax/fail2ban}:${IMAGE_TAG:-latest}
  network_mode: host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  restart: always

x-environment:
  &environment-common
  TZ:
  F2B_LOG_LEVEL:
  F2B_DB_PURGE_AGE:
  F2B_MAX_RETRY:
  F2B_DEST_EMAIL:
  F2B_SENDER:
  F2B_ACTION:
  SSMTP_HOSTNAME:
  SSMTP_HOST:
  SSMTP_PORT:
  SSMTP_USER:
  SSMTP_PASSWORD:
  SSMTP_TLS:
  TTS_DND_START:
  TTS_DND_END:
  TTS_START_TEXT:
  TTS_STOP_TEXT:
  TTS_BAN_TEXT:
  TTS_UNBAN_TEXT:
  TTS_URL:
  TTS_USER:
  TTS_PASS:
  TTS_VOICE:
  TTS_LANGUAGE:
  TTS_PITCH:
  TTS_TEMPO:
  TTS_DELAY:
  TTS_SLOW_READING:

services:
  fail2ban-input:
    << : *fail2ban-common
    container_name: ${INPUT_CONTAINER_NAME}
    environment:
      << : *environment-common
      F2B_IPTABLES_CHAIN: INPUT
    volumes:
      - data-input-vol:/data
      - ${SSH_LOG_PATH:-/var/log}:/log/ssh:ro
    secrets:
      - source: jail-ssh
        target: /data/jail.d/ssh.conf
      - source: action-tts
        target: /data/action.d/tts.conf

  fail2ban-docker:
    << : *fail2ban-common
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      << : *environment-common
      F2B_IPTABLES_CHAIN: DOCKER-USER
    volumes:
      - data-docker-vol:/data
      - traefik-log-vol:/log/traefik:ro
      - mail-log-vol:/log/mail:ro
    secrets:
      - source: filter-traefik
        target: /data/filter.d/traefik.conf
      - source: jail-traefik
        target: /data/jail.d/traefik.conf
      - source: jail-mail
        target: /data/jail.d/mail.conf
      - source: action-tts
        target: /data/action.d/tts.conf

volumes:
  data-input-vol:
    name: ${DATA_INPUT_VOL_NAME:-fail2ban-data-input-vol}

  data-docker-vol:
    name: ${DATA_DOCKER_VOL_NAME:-fail2ban-data-docker-vol}

  traefik-log-vol:
    name: ${TRAEFIK_LOG_VOL_NAME:-traefik-log-vol}
    external: true

  mail-log-vol:
    name: ${MAIL_LOG_VOL_NAME:-mail-log-vol}
    external: true

secrets:
  filter-traefik:
    file: ./config/filter.d/traefik.conf

  jail-traefik:
    file: ./config/jail.d/traefik.conf

  jail-ssh:
    file: ./config/jail.d/ssh.conf

  jail-mail:
    file: ./config/jail.d/mail.conf

  action-tts:
    file: ./config/action.d/tts.conf
