version: '2.4'

x-fail2ban:
  &fail2ban-common
  image: ${IMAGE_NAME:-crazymax/fail2ban}:${IMAGE_TAG:-latest}
  network_mode: host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  restart: always
  cpus: '${CPUS:-0.5}'
  mem_limit: ${MEM_LIMIT:-64M}
  mem_reservation: ${MEM_RESERVATION:-32M}

x-environment:
  &environment-common
  TZ:
  F2B_LOG_LEVEL:
  F2B_DB_PURGE_AGE:
  SSMTP_HOSTNAME:
  SSMTP_HOST:
  SSMTP_PORT:
  SSMTP_USER:
  SSMTP_PASSWORD:
  SSMTP_TLS:
  TTS_DND_START:
  TTS_DND_END:
  TTS_START_TEXT:
  TTS_STOP_TEXT:
  TTS_BAN_TEXT:
  TTS_UNBAN_TEXT:
  TTS_URL:
  TTS_USER:
  TTS_PASS:
  TTS_VOICE:
  TTS_LANGUAGE:
  TTS_PITCH:
  TTS_TEMPO:
  TTS_DELAY:
  TTS_SLOW_READING:

services:
  fail2ban-input:
    << : *fail2ban-common
    environment:
      << : *environment-common

  fail2ban-docker:
    << : *fail2ban-common
    environment:
      << : *environment-common
