version: '2.4'

services:
  fail2ban-input:
    container_name: ${INPUT_CONTAINER_NAME:-fail2ban-input}
    volumes:
      - data-input-vol:/data
      - ${SSH_LOG_PATH:-/var/log}:/log/ssh:ro
      - ./config/jail.d/default.conf:/data/jail.d/default.conf:ro
      - ./config/jail.d/ssh.conf:/data/jail.d/ssh.conf:ro
      - ./config/action.d/tts.conf:/data/action.d/tts.conf:ro
      - ./config/action.d/sendmail-whois-lines.local:/data/action.d/sendmail-whois-lines.local:ro

volumes:
  data-input-vol:
    name: ${DATA_INPUT_VOL_NAME:-fail2ban-data-input-vol}
